<a href="https://colab.research.google.com/github/dhruvUpmanyu-01/Supervised-Learning/blob/main/Lab1_Dhruv_Upmanyu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Hindi = int(input("Enter the Hindi marks : "))
English = int(input("Enter the English marks : "))
Maths = int(input("Enter the Maths marks : "))
Science = int(input("Enter the Science marks : "))
SST = int(input("Enter the SST marks : "))

Total_Marks = (Hindi + English + Maths + Science + SST)
print("Total Marks : ", Total_Marks)

Percentage = (Total_Marks/500)*100
print("Percentage : ", Percentage)

if ( Percentage >= 90 ):
    print("Grade : O")
elif ( Percentage >= 80 ):
    print("Grade : A+")
elif ( Percentage >= 70 ):
    print("Grade : A")
elif ( Percentage >= 60 ):
    print("Grade : B+")
elif ( Percentage >= 50 ):
    print("Grade : B")
elif ( Percentage >= 40 ):
    print("Grade : C")
else:
    print("Fail")

Enter the Hindi marks : 90
Enter the English marks : 75
Enter the Maths marks : 100
Enter the Science marks : 85
Enter the SST marks : 80
Total Marks :  430
Percentage :  86.0
Grade : A+


In [ ]:
import numpy as np

To create a Numpy array containing only zeros we use np.zeros

In [ ]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
type(a[0])

numpy.float64

If wenwant to use integers we can specify as follows:

In [ ]:
a = np.zeros(3, dtype=int)
a

array([0, 0, 0])

In [ ]:
z = np.zeros(10)

In [ ]:
z.shape

(10,)

Here we got a comma because it represents a tuple..if we don't use a comma it will represent normal 10

In [ ]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z.shape = (10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
z = np.zeros(4)
z.shape = (2,2)
z

array([[0., 0.],
       [0., 0.]])

In [ ]:
z = np.linspace(2,4,5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
z = np.identity(2)
z

array([[1., 0.],
       [0., 1.]])

In [ ]:
z = np.array([10,20])
z

array([10, 20])

In [ ]:
type(z)

numpy.ndarray

In [ ]:
z = np.array([[1,2],[3,4]])
z

array([[1, 2],
       [3, 4]])

In [ ]:
z = np.linspace(1,2,5)
z

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
z[0]

1.0

In [ ]:
z[0:2]

array([1.  , 1.25])

In [ ]:
z[-1]

2.0

In [ ]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
x[0,0]

1

In [ ]:
x[0, : ]

array([1, 2])

In [ ]:
y = np.array([[7,5,21],[11,8,3],[5,15,12]])
y

array([[ 7,  5, 21],
       [11,  8,  3],
       [ 5, 15, 12]])

In [ ]:
y[0, : ]

array([ 7,  5, 21])

In [ ]:
y[ : ,0]

array([ 7, 11,  5])

In [ ]:
y[1, : ]

array([11,  8,  3])

In [ ]:
y[2, : ]

array([ 5, 15, 12])

In [ ]:
y[ : ,1]

array([ 5,  8, 15])

In [ ]:
y[ : ,2]

array([21,  3, 12])

In [ ]:
z = np.linspace(2,4,5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
indices = np.array((0,2,3))
z[indices]

array([2. , 3. , 3.5])

In [ ]:
d = np.array([0,5,1,0,0], dtype=bool)
d

array([False,  True,  True, False, False])

In [ ]:
a = np.array((11,23,15,92,45,76,23,87,15,12))
a

array([11, 23, 15, 92, 45, 76, 23, 87, 15, 12])

In [ ]:
a.sort()
a

array([11, 12, 15, 15, 23, 23, 45, 76, 87, 92])

the chages will be reflected in the original array as well


In [ ]:
a

array([11, 12, 15, 15, 23, 23, 45, 76, 87, 92])

In [ ]:
a.sum()

399

In [ ]:
a.mean()

39.9

In [ ]:
a.max()

92

In [ ]:
a.min()

11

In [ ]:
a.argmax()

9

it will return the index of the maximum number

In [ ]:
a.argmin()

0

In [ ]:
a.argmin()

0

In [ ]:
a.cumsum()

array([ 11,  23,  38,  53,  76,  99, 144, 220, 307, 399])

In [ ]:
a.cumprod()

array([             11,             132,            1980,           29700,
                683100,        15711300,       707008500,     53732646000,
         4674740202000, 430076098584000])

In [ ]:
a.var()

968.6899999999999

In [ ]:
a.std()

31.12378511685235

In [ ]:
a.searchsorted(76)

7

In [ ]:
np.sum(a)

399

In [ ]:
np.sort(a)

array([11, 12, 15, 15, 23, 23, 45, 76, 87, 92])

In [ ]:
np.min(a)

11

In [ ]:
np.max(a)

92

In [ ]:
np.mean(a)

39.9

In [ ]:
np.var(a)

968.6899999999999

In [ ]:
np.argmax(a)

3

In [ ]:
a = np.array([2,2,2,2])
b = np.array([3,3,3,3])
a + b

array([5, 5, 5, 5])

In [ ]:
a * b

array([6, 6, 6, 6])

In [ ]:
a + 10

array([12, 12, 12, 12])

In [ ]:
a * 10

array([20, 20, 20, 20])

In [ ]:
a

array([2, 2, 2, 2])

In [ ]:
X = np.array([[1,2,3],[4,3,4],[4,3,4]])
Y = np.array([[5,6,9],[4,7,8],[4,3,4]])


In [ ]:
X + Y

array([[ 6,  8, 12],
       [ 8, 10, 12],
       [ 8,  6,  8]])

In [ ]:
X + 10

array([[11, 12, 13],
       [14, 13, 14],
       [14, 13, 14]])

VECTOR IN PYTHON IS A DATA POINT.

In [ ]:
X @ Y

array([[25, 29, 37],
       [48, 57, 76],
       [48, 57, 76]])

In [ ]:
X.T

array([[1, 4, 4],
       [2, 3, 3],
       [3, 4, 4]])

In [ ]:
X == Y

array([[False, False, False],
       [ True, False, False],
       [ True,  True,  True]])

In [ ]:
X > 5

array([[False, False, False],
       [False, False, False],
       [False, False, False]])